# Generated by Django 4.2.6 on 2023-10-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_appointment_status_user_license_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ssn',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
