# Generated by Django 4.2.6 on 2023-10-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pet_age_user_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service_provider',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
