# Generated by Django 3.2.22 on 2023-12-12 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_searchhistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='pet_name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='ssn',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='vaccination_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
